
export const LOAD_BETSLIPS = 'LOAD_BETSLIPS';

export const ADD_BETSLIP_REQUEST = 'ADD_BETSLIP_REQUEST';
export const ADD_BETSLIP_SUCCESS = 'ADD_BETSLIP_SUCCESS';
export const ADD_BETSLIP_FAIL = 'ADD_BETSLIP_FAIL';

export const REMOVE_BETSLIP_REQUEST = 'REMOVE_BETSLIP_REQUEST';
export const REMOVE_BETSLIP_SUCCESS = 'REMOVE_BETSLIP_SUCCESS';
export const REMOVE_BETSLIP_FAIL = 'REMOVE_BETSLIP_FAIL';
